# Generated by Django 4.1.7 on 2023-03-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_attendancereport_attendance_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminHOD',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Users',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (3, 'User')], default=1, max_length=10),
        ),
    ]
