# Generated by Django 4.1.7 on 2023-03-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_adminhod_admin_rename_students_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='college',
            field=models.CharField(choices=[('Select your college/department', 'Select your college/department'), ('COE', 'College of Engineering'), ('CON', 'College of Nursing'), ('CISC', 'College of Information Sciences and Computing'), ('CBM', 'College of Business Management'), ('CAS', 'College of Arts and Sciences'), ('CFES', 'College of Forestry and Environmental Science'), ('COA', 'College of Agriculture'), ('COED', 'College of Education'), ('CVM', 'College of Veterinary Medicine'), ('Other', 'Other Office'), ('Dugangan pa', 'Dugangan pa')], default='No College Selected', max_length=100, verbose_name='College/Department'),
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(default='No Country added', max_length=30, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='no first name specified', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='hometown',
            field=models.CharField(default='No hometown added', max_length=30, verbose_name='Hometown'),
        ),
        migrations.AddField(
            model_name='users',
            name='house_type',
            field=models.CharField(choices=[('Select your house type', 'Select your house type'), ('Private House', 'Private House'), ('Cottage', 'Cottage')], default='No house type selecetd', max_length=50, verbose_name='House Type'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='no last name specified', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='marital_status',
            field=models.CharField(choices=[('Select your marital status', 'Selects your marital status'), ('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], default='No status selected', max_length=50, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='users',
            name='middle_name',
            field=models.CharField(default='no middle name specified', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='nationality',
            field=models.CharField(default='No nationality added', max_length=30, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='users',
            name='office',
            field=models.CharField(default='No office added', max_length=50, verbose_name='Office'),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(default='No number added', max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='users',
            name='salary',
            field=models.CharField(choices=[('Select your current salary', 'Select your current salary'), ('below 15,000 php', 'below 15,000 php'), ('15,001 - 20,000 php', '15,000 - 20,000 php'), ('20,001 - 30,000 php', '20,001 - 30,000 php'), ('30,001 - 40,000 php', '30,001 - 40,000 php'), ('40,001 - 50,000 php', '40,001 - 50,000 php'), ('50,001 - 60,000 php', '50,001 - 60,000 php'), ('60,001 - 70,000 php', '60,001 - 70,000 php'), ('70,001 - 80,000 php', '70,001 - 80,000 php'), ('80,001 - 90,000 php', '80,001 - 90,000 php'), ('90,001 - 100,000 php', '90,001 - 100,000 php'), ('More than 100,001+php', 'More than 100,000 php')], default='No salary selected', max_length=50, verbose_name='Monthly Salary'),
        ),
        migrations.AlterField(
            model_name='users',
            name='job',
            field=models.CharField(default='no job specified', max_length=50),
        ),
    ]
