# Generated by Django 4.1.7 on 2023-03-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_users_college_users_country_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='no last name specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='middle_name',
            field=models.CharField(default='no middle name specified', max_length=50),
        ),
    ]
