# Generated by Django 4.1.7 on 2023-03-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_users_first_name_alter_users_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='college',
        ),
    ]
