# Generated by Django 4.1.7 on 2023-03-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_users_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
    ]
