# Generated by Django 4.1.7 on 2023-03-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_users_college_users_first_name_users_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='college',
            new_name='college1',
        ),
    ]
