# Generated by Django 4.1.7 on 2023-03-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_college_users_college1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='college1',
            new_name='college',
        ),
    ]
