# Generated by Django 4.1.7 on 2023-03-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_users_college_alter_users_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='marital_status',
            field=models.CharField(choices=[('Select your marital status', 'Select your marital status'), ('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=30, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nationality',
            field=models.CharField(max_length=20, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='users',
            name='salary',
            field=models.CharField(choices=[('Select your current salary', 'Select your current salary'), ('below 15,000 php', 'below 15,000 php'), ('15,001 - 20,000 php', '15,000 - 20,000 php'), ('20,001 - 30,000 php', '20,001 - 30,000 php'), ('30,001 - 40,000 php', '30,001 - 40,000 php'), ('40,001 - 50,000 php', '40,001 - 50,000 php'), ('50,001 - 60,000 php', '50,001 - 60,000 php'), ('60,001 - 70,000 php', '60,001 - 70,000 php'), ('70,001 - 80,000 php', '70,001 - 80,000 php'), ('80,001 - 90,000 php', '80,001 - 90,000 php'), ('90,001 - 100,000 php', '90,001 - 100,000 php'), ('More than 100,001+php', 'More than 100,000 php')], max_length=30, verbose_name='Monthly Salary'),
        ),
    ]
