# Generated by Django 4.1.7 on 2023-03-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_users_address_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='college',
            field=models.CharField(max_length=50, verbose_name='College/Department'),
        ),
        migrations.AlterField(
            model_name='users',
            name='house_type',
            field=models.CharField(max_length=25, verbose_name='House Type'),
        ),
        migrations.AlterField(
            model_name='users',
            name='marital_status',
            field=models.CharField(max_length=30, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='salary',
            field=models.CharField(max_length=30, verbose_name='Monthly Salary'),
        ),
    ]
