# Generated by Django 4.1.7 on 2023-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_users_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='college',
            field=models.CharField(choices=[('Select your college/department', 'Select your college/department'), ('COE', 'College of Engineering'), ('CON', 'College of Nursing'), ('CISC', 'College of Information Sciences and Computing'), ('CBM', 'College of Business Management'), ('CAS', 'College of Arts and Sciences'), ('CFES', 'College of Forestry and Environmental Science'), ('COA', 'College of Agriculture'), ('COED', 'College of Education'), ('CVM', 'College of Veterinary Medicine'), ('Other', 'Other Office'), ('Dugangan pa', 'Dugangan pa')], max_length=50, verbose_name='College/Department'),
        ),
        migrations.AlterField(
            model_name='users',
            name='house_type',
            field=models.CharField(choices=[('Select your house type', 'Select your house type'), ('Private House', 'Private House'), ('Cottage', 'Cottage')], max_length=25, verbose_name='House Type'),
        ),
        migrations.AlterField(
            model_name='users',
            name='marital_status',
            field=models.CharField(choices=[('Select your marital status', 'Select your marital status'), ('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=30, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='salary',
            field=models.CharField(choices=[('Select your current salary', 'Select your current salary'), ('below 15,000 php', 'below 15,000 php'), ('15,001 - 20,000 php', '15,000 - 20,000 php'), ('20,001 - 30,000 php', '20,001 - 30,000 php'), ('30,001 - 40,000 php', '30,001 - 40,000 php'), ('40,001 - 50,000 php', '40,001 - 50,000 php'), ('50,001 - 60,000 php', '50,001 - 60,000 php'), ('60,001 - 70,000 php', '60,001 - 70,000 php'), ('70,001 - 80,000 php', '70,001 - 80,000 php'), ('80,001 - 90,000 php', '80,001 - 90,000 php'), ('90,001 - 100,000 php', '90,001 - 100,000 php'), ('More than 100,001+php', 'More than 100,000 php')], max_length=30, verbose_name='Monthly Salary'),
        ),
    ]
